WebClient/Areas/Admin/Controllers/AdminLecturerGroupController.cs
using System;
using System.Collections.Generic;
using AutoMapper;
using BLL.Contract;
using CMSys_project.ViewModels;
using Domain.Entities.UserEntities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CMSys_project.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Route("Admin/LecturerGroup")]
    [Authorize(Roles = "Administrator")]
    public class AdminLecturerGroupController : Controller
    {
        private readonly ICatalogService _iCatalogService;
        private readonly IMapper _iMapper;

        public AdminLecturerGroupController(ICatalogService iCatalogService, IMapper iMapper)
        {
            _iCatalogService = iCatalogService;
            _iMapper = iMapper;
        }

        [Route("Info")]
        public IActionResult Info()
        {
            IEnumerable<LecturerGroupVM> LecturerGroupVMs =
               _iMapper.Map<IEnumerable<LecturerGroup>, IEnumerable<LecturerGroupVM>>(_iCatalogService.GetAllLecturerGroup());
            return View("Info", LecturerGroupVMs);
        }

        [Route("Create")]
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [Route("Create")]
        [HttpPost]
        public IActionResult Create(LecturerGroupVM LecturerGroup)
        {
            if (!ModelState.IsValid)
            {
                return View(LecturerGroup);
            }
            LecturerGroup.Id = Guid.NewGuid();
            LecturerGroup LecturerGr = _iMapper.Map<LecturerGroupVM, LecturerGroup>(LecturerGroup);
            try
            {
                _iCatalogService.AddLecturerGroup(LecturerGr);
                return RedirectToAction("Info");

            }
            catch
            {

                ViewBag.Role = "Admin";
                ViewBag.Message = $"Lecturer Group with name {LecturerGr.Name} is already existed";
                return View("Error");
            }

        }

        [Route("Edit/{id}")]
        [HttpGet]
        public IActionResult Edit(Guid id)
        {
            LecturerGroup LecturerGroup = _iCatalogService.GetLecturerGroup(id);
            LecturerGroupVM LecturerGr = _iMapper.Map<LecturerGroup, LecturerGroupVM>(LecturerGroup);
            if (LecturerGroup != null)
            {
                return View(LecturerGr);
            }

            ViewBag.Role = "Admin";
            ViewBag.Message = "Lecturer Group was not found";
            return View("Error");
        }

        [Route("Edit/{id}")]
        [HttpPost]
        public IActionResult Edit(LecturerGroupVM LecturerGroup)
        {
            if (!ModelState.IsValid)
            {
                return View(LecturerGroup);
            }
            LecturerGroup LecturerGr = _iMapper.Map<LecturerGroupVM, LecturerGroup>(LecturerGroup);
            try
            {
                _iCatalogService.EditLecturerGroup(LecturerGr);
                return RedirectToAction("Info");
            }
            catch
            {
                ViewBag.Role = "Admin";
                ViewBag.Message = $"Department with name {LecturerGr.Name} is already existed";
                return View("Error");
            }
        }

        [Route("Delete/{id}")]
        [HttpGet]
        [ActionName("Delete")]
        public IActionResult ConfirmDelete(Guid id)
        {
            {
                LecturerGroup LecturerGroup = _iCatalogService.GetLecturerGroup(id);
                LecturerGroupVM LecturerGroupVm = _iMapper.Map<LecturerGroup, LecturerGroupVM>(LecturerGroup);

                if (LecturerGroupVm != null)
                {
                    int countLecturers = LecturerGroup.Lecturer.Count;
                    if (countLecturers != 0)
                    {
                        ViewBag.Role = "Admin";
                        ViewBag.Message = $"Department has dependents and cannot be deleted:  Course: {countLecturers}";
                        return View("Error");
                    }
                    return View(LecturerGroupVm);
                }
            }

            ViewBag.Role = "Admin";
            ViewBag.Message = "Lecturer group was not found";
            return View("Error");
        }

        [Route("Delete/{id}")]
        [HttpPost]
        public IActionResult Delete(Guid id)
        {

            LecturerGroup LecturerGroup = _iCatalogService.GetLecturerGroup(id);
            if (LecturerGroup != null && LecturerGroup.Lecturer.Count == 0)
            {
                _iCatalogService.DeleteLecturerGroup(LecturerGroup.Id);
                return RedirectToAction("Info");
            }

            ViewBag.Role = "Admin";
            ViewBag.Message = "Lecturer group was not found";
            return View("Error");
        }

        [Route("Error")]
        public IActionResult Error()
        {
            return View("Error");
        }
    }
}

WebClient/Areas/Admin/Views/AdminLecturerGroup/Create.cshtml
@model CMSys_project.ViewModels.LecturerGroupVM
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    ViewBag.Title = "Add lecturer group";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Main{
    <form asp-action="Create" asp-controller="AdminLecturerGroup">
        <div class="form-group">
            <label asp-for="Name" class="control-label">Name</label>
            <input type="text" asp-for="Name" class="form-control"/>
            <span asp-validation-for="Name"></span>
        </div>
        <div class="form-group">
            <input type="submit" value="Send" class="btn btn-success" style="background-color:darkseagreen"/>
        </div>
    </form>
}

@section validation {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

WebClient/Areas/Admin/Views/AdminLecturerGroup/Delete.cshtml
@model CMSys_project.ViewModels.LecturerGroupVM
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    ViewData["Title"] = "Delete Lecturer group";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Main
{
    <div>
        <dl class="dl-horizontal">
            <dt>Name</dt>
            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>

        </dl>

        <div>
            <div class="alert alert-warning" role="alert">
                Delete this Department?
            </div>
            <div>
                <form style="display: inline-block" asp-controller="AdminLecturerGroup" asp-action="Delete" method="post">
                    <button type="submit" class="btn btn-success" style="background-color:darkseagreen">Yes</button>
                </form>
                <form style="display: inline-block" asp-controller="AdminLecturerGroup" asp-action="Info" method="post">
                    <button type="submit" class="btn btn-primary" style="background-color: #ADD8E6">No</button>
                </form>
            </div>
        </div>
    </div>
}

WebClient/Areas/Admin/Views/AdminLecturerGroup/Edit.cshtml
@model CMSys_project.ViewModels.LecturerGroupVM
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers


@{
    ViewBag.Title = "Edit Lecturer Group";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Main{
    <form asp-action="edit" asp-controller="AdminLecturerGroup" asp-route-id="@Model.Id">
        <div class="form-group">
            <label asp-for="Name" class="control-label">Name</label>
            <input type="text" asp-for="Name" class="form-control"/>
            <span asp-validation-for="Name"></span>
        </div>
        <div class="form-group">
            <input type="submit" value="Send" class="btn btn-success" style="background-color:darkseagreen"/>
        </div>
    </form>
}

@section validation {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

WebClient/Areas/Admin/Views/AdminLecturerGroup/Info.cshtml
@using CMSys_project.ViewModels
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    ViewBag.Title = "lecturer Groups";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Main{
    <h2>lecturer groups</h2>
    <div class="form-group">
        <a class="btn btn-secondary btn-lg" asp-action="Create">Add group</a>
    </div>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>Name</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>
        @foreach (LecturerGroupVM item in Model)
        {
            <tr>
                <td>@item.Name</td>
                <td>
                    <a class="btn btn-outline-dark" asp-action="Edit" asp-controller="AdminLecturerGroup" asp-route-id="@item.Id">Edit</a>
                    <a class="btn btn-outline-dark" asp-action="Delete" asp-controller="AdminLecturerGroup" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
        </tbody>
    </table>
}