WebClient/Areas/Admin/Controllers/AdminCourseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using AutoMapper;
using BLL.Contract;
using CMSys_project.ViewModels;
using Domain.Entities.CourseEntities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace CMSys_project.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Route("Admin/Course")]
    [Authorize(Roles = "Administrator")]
    public class AdminCourseController : Controller
    {
        private readonly ICatalogService _iCatalogService;
        private readonly IMembershipService _iMembershipService;
        private readonly IMapper _iMapper;

        public AdminCourseController(ICatalogService iCatalogService,
            IMapper iMapper, IMembershipService imembershipService)
        {
            _iCatalogService = iCatalogService;
            _iMapper = iMapper;
            _iMembershipService = imembershipService;
        }

        [Route("Info")]
        public IActionResult Info()
        {
           // string id = User.Claims.Where(x => x.Type == ClaimTypes.Name).First().Value;
           IEnumerable<CourseVM> CourseVms =
               _iMapper.Map<IEnumerable<Course>, IEnumerable<CourseVM>>(_iCatalogService.GetAllCourse());
               // .Where(x => x.LecturerCourse.Where(y => y.Email.ToString() == id).Count()
                 //           > 0));
            return View("Info", CourseVms);
        }

        [Route("Create")]
        [HttpGet]
        public IActionResult Create()
        {
            ViewData.Model = new CourseVM
            {
                Departments = new SelectList(_iCatalogService.GetAllDepartment(), "Id", "Name"),
                Lecturers = new List<LecturerVM>(),
                Department = null
            };

            return View();
        }

        [Route("Create")]
        [HttpPost]
        public IActionResult Create(CourseVM course)
        {
            if (!ModelState.IsValid)
            {
                course.Departments = new SelectList(_iCatalogService.GetAllDepartment(), "Id", "Name");
                return View(course);
            }

            course.Id = Guid.NewGuid();
            Course courseGr = _iMapper.Map<CourseVM, Course>(course);

            try
            {
                _iCatalogService.AddCourse(courseGr);
                return RedirectToAction("Info");
            }
            catch
            {
                ViewBag.Message = "Something goes wrong!";
                return View("Error");
            }
        }

        [Route("Edit/{id}")]
        [HttpGet]
        public IActionResult Edit(Guid id)
        {
            Course course = _iCatalogService.GetCourse(id);
            CourseVM courseVm;
            try
            {
                courseVm = _iMapper.Map<Course, CourseVM>(course);
                courseVm.Departments = new SelectList(
                    _iCatalogService.GetAllDepartment().Select(t => new {t.Id, t.Name}),
                    "Id", "Name");
                ViewData.Model = courseVm;
            }
            catch
            {
                ViewBag.Message = "Course was not found";
                return View("Error");
            }

            return View(courseVm);
        }

        [Route("Edit/{id}")]
        [HttpPost]
        public IActionResult Edit(CourseVM courseVm)
        {
            if (!ModelState.IsValid)
            {
                courseVm.Departments = new SelectList(
                    _iCatalogService.GetAllDepartment().Select(t => new {t.Id, t.Name}),
                    "Id", "Name");
                return View(courseVm);
            }

            try
            {
                Course course = _iMapper.Map<CourseVM, Course>(courseVm);
                _iCatalogService.EditCourse(course);
                return RedirectToAction("Info");
            }

            catch
            {
                ViewBag.Message = "Course was not found";
                return View("Error");
            }
        }

        [Route("Delete/{id}")]
        [HttpGet]
        [ActionName("Delete")]
        public IActionResult ConfirmDelete(Guid id)
        {
            {
                Course course = _iCatalogService.GetCourse(id);
                CourseVM courseVm = _iMapper.Map<Course, CourseVM>(course);

                if (courseVm != null)
                {
                    int countCourses = course.LecturerCourse.Count;
                    if (countCourses != 0)
                    {
                        ViewBag.Message = $"Course has dependents and cannot be deleted:  Course: {countCourses}";
                        return View("Error");
                    }

                    return View(courseVm);
                }
            }

            ViewBag.Message = "Course was not found";
            return View("Error");
        }

        [Route("Delete/{id}")]
        [HttpPost]
        public IActionResult Delete(Guid id)
        {
            {
                Course course = _iCatalogService.GetCourse(id);
                if (course != null && course.LecturerCourse.Count == 0)
                {
                    _iCatalogService.DeleteCourse(course.Id);
                    return RedirectToAction("Info");
                }
            }

            ViewBag.Message = "Course was not found";
            return View("Error");
        }

        [Route("Error")]
        public IActionResult Error()
        {
            return View("Error");
        }

        [Route("EditLecturer/{id}")]
        [HttpGet]
        public IActionResult EditLecturer(Guid id)
        {
            Course course = _iCatalogService.GetCourse(id);
            try
            {
                CourseVM courseVm = _iMapper.Map<Course, CourseVM>(course);

                courseVm.AllTheLecturers = new SelectList(_iCatalogService.GetAllLecturer()
                    .Except(_iCatalogService.GetCourseLecturers(course))
                    .Select(t => new {Id = t.UserId, FullName = $"{t.User.Name} {t.User.Surname}"}), "Id", "FullName");
                ViewData.Model = courseVm;
            }

            catch (Exception)
            {
                ViewBag.Message = "Course was not found";
                return View("Error");
            }

            if (course != null)
            {
                return View();
            }

            ViewBag.Message = "Course was not found";
            return View("Error");
        }


        [Route("EditLecturer/DeleteLecturer")]
        public IActionResult DeleteLecturer(Guid courseId, Guid LecturerId)
        {
            _iCatalogService.DeleteCourseLecturer(_iCatalogService.GetCourse(courseId),
                _iCatalogService.GetLecturer(LecturerId));
            return RedirectToAction("EditLecturer", new {id = courseId});
        }

        [Route("EditLecturer/AddLecturer")]
        public IActionResult AddLecturer(Guid courseId, CourseVM course)
        {
            course.Id = courseId;
            _iCatalogService.AddLecturerCourse(_iCatalogService.GetCourse(course.Id),
                _iCatalogService.GetLecturer(course.SelectedLecturer));
            return RedirectToAction("EditLecturer", new {id = course.Id});
        }

        [Route("Profile/{id}")]
        public IActionResult Profile(Guid id)
        {
            Course course = _iCatalogService.GetCourse(id);
            ViewData.Model = _iMapper.Map<Course, CourseVM>(course);
            if (course is null)
            {
                ViewBag.Message = "Course was not found";
                return View("Error");
            }

            return View();
        }
    }
}

WebClient/Areas/User/Controllers/UserCourseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using AutoMapper;
using BLL.Contract;
using CMSys_project.Helpers;
using CMSys_project.ViewModels;
using Domain.Entities.CourseEntities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CMSys_project.Areas.User.Controllers
{
    [Area("User")]
    [Authorize(Roles = "User, Administrator, Lecturer")]
    [Route("")]
    [Route("User/Course")]
    public class UserCourseController : Controller
    {
        private readonly ICatalogService _iCatalogService;
        private readonly IMembershipService _iMembershipService;
        private readonly IMapper _iMapper;

        public UserCourseController(ICatalogService iCatalogService, IMapper iMapper, IMembershipService iMembershipService)
        {
            _iCatalogService = iCatalogService;
            _iMembershipService = iMembershipService;
            _iMapper = iMapper;
        }
        [Route("")]
        [Route("Info")]
        public IActionResult Info()
        {
            IEnumerable<CourseVM> DepartmentVms =
                _iMapper.Map<IEnumerable<Course>, IEnumerable<CourseVM>>(_iCatalogService.GetAllCourse());
            return View("Info", DepartmentVms);

        }

        [Route("Error")]
        public IActionResult Error()
        {
            return View("Error");
        }

        [Route("Profile/{id}")]
        public IActionResult Profile(Guid id)
        {

            Course course = _iCatalogService.GetCourse(id);
            ViewData.Model = _iMapper.Map<Course, CourseVM>(course);
            if (course is null)
            {
                ViewBag.Message = "Course was not found";
                return View("Error");
            }

            return View();
        }

        [Route("Subscribe/{id}")]
        [HttpGet]
        [ActionName("Subscribe")]
        public IActionResult SubscribeInfo(Guid id)
        {
            Course course = _iCatalogService.GetCourse(id);
            CourseVM courseVm = _iMapper.Map<Course, CourseVM>(course);
            if (course is null)
            {
                ViewBag.Message = "Course was not found";
                return View("Error");
            }
            return View(courseVm);
        }

        [Route("Subscribe/{id}")]
        [HttpPost]
        public IActionResult Subscribe(Guid idd)
        {
            string id = User.Claims.First(x => x.Type == ClaimTypes.Name).Value;
            Domain.Entities.UserEntities.User user = _iMembershipService.GetUser(Guid.Parse(id));
            Course course = _iCatalogService.GetCourse(idd);
            foreach (LecturerCourse lecturerCourse in course.LecturerCourse)
            {
                SNS.SendMessageAsync("senderfromapp@gmail.com", "feria8000@gmail.com", user.Email, user.Name + " " + user.Surname, user.Faculty, course.Name,
                    "12345678_k");
            }

            return RedirectToAction("Info");
        }

    }
}

WebClient/Areas/Admin/Views/AdminCourse/Create.cshtml
@using CMSys_project.ViewModels
@model CMSys_project.ViewModels.CourseVM
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Add Course";
}

@section Main{
    <form asp-action="Create" asp-controller="UserCourse">
        <div class="form-group">
            <label asp-for="Name" class="control-label">Name</label>
            <input type="text" asp-for="Name" class="form-control"/>
            <span asp-validation-for="Name"></span>
        </div>
        <div class="form-group">
            <label>New course</label>
            <div class="form-group">
                <input type="checkbox" asp-for="Status"/>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Type"></label>
            <div class="form-group">
                <select asp-for="Type" asp-items="Html.GetEnumSelectList<CourseTypeVM>()">
                </select>
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Schedule"></label>
            <div class="form-group">
                <select asp-for="Schedule" asp-items="Html.GetEnumSelectList<WayPlanningVM>()">
                </select>
                <span asp-validation-for="Schedule" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label>Department</label>
            <select class="form-control" asp-for="GroupCourseId" asp-items="@Model.Departments"></select>
            <span asp-validation-for="GroupCourseId"></span>
        </div>
        <div class="form-group">
            <label>Description</label>
            <div class="form-group">
                <input type="text" asp-for="Description" class="form-control"/>
                <span asp-validation-for="Description"></span>
            </div>
        </div>
        <div class="form-group">
            <input type="submit" value="Send" class="btn btn-success" style="background-color:darkseagreen"/>
        </div>
    </form>
}

@section validation {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

WebClient/Areas/Admin/Views/AdminCourse/Delete.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@model CMSys_project.ViewModels.CourseVM
@{
    ViewData["Title"] = "Delete Course";
}

@section Main
{
    <div>
        <dl class="dl-horizontal">
            <dt>Name</dt>
            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>

        </dl>

        <div>
            <div class="alert alert-warning" role="alert">
                Delete this course?
            </div>
            <div>
                <form style="display: inline-block" asp-controller="AdminCourse" asp-action="Delete" method="post">
                    <button type="submit" class="btn btn-success" style="background-color:darkseagreen">Yes</button>
                </form>
                <form style="display: inline-block" asp-controller="AdminCourse" asp-action="Info" method="post">
                    <button type="submit" class="btn btn-primary" style="background-color: #ADD8E6">No</button>
                </form>
            </div>
        </div>
    </div>
}

WebClient/Areas/Admin/Views/AdminCourse/Edit.cshtml
@using CMSys_project.ViewModels
@model CMSys_project.ViewModels.CourseVM
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    Layout = "~/Views/Shared/_Layout.cshtml";

    ViewBag.Title = "Edit Course";
}

@section Main{
    <form asp-action="edit" asp-controller="AdminCourse" asp-route-id="@Model.Id">
        <div class="form-group">
            <label>Name</label>
            <div class="form-group">
                <input type="text" asp-for="Name" class="form-control"/>
                <span asp-validation-for="Name"></span>
            </div>
        </div>
        <div class="form-group">
            <label>New course</label>
            <div class="form-group">
                <input type="checkbox" asp-for="Status"/>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="Type"></label>
            <div class="form-group">
                <select asp-for="Type" asp-items="Html.GetEnumSelectList<CourseTypeVM>()">
                </select>
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Schedule"></label>
            <div class="form-group">
                <select asp-for="Schedule" asp-items="Html.GetEnumSelectList<WayPlanningVM>()">
                </select>
                <span asp-validation-for="Schedule" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label>Department</label>
            <select class="form-control" asp-for="GroupCourseId" asp-items="@Model.Departments"></select>
        </div>
        <div class="form-group">
            <label>Description</label>
            <div class="form-group">
                <input type="text" asp-for="Description" class="form-control"/>
                <span asp-validation-for="Description"></span>
            </div>
        </div>
        <div class="form-group">
            <input type="submit" value="Send" class="btn btn-success" style="background-color:darkseagreen"/>
        </div>
    </form>
}

@section validation {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

WebClient/Areas/Admin/Views/AdminCourse/EditLecturer.cshtml
@using CMSys_project.ViewModels
@model CMSys_project.ViewModels.CourseVM
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Edit Lecturers";
}

@section Main{
    <h2>@Model.Name</h2>
    <hr/>

    <table class="table table-bordered">
        <tr>
            <td>Profile</td>
            <td>Action</td>
        </tr>
        @{
            foreach (LecturerVM Lecturer in Model.Lecturers)
            {
                <tr>
                    <td>
                        @Lecturer.User.FullName
                    </td>
                    <td>
                        <a asp-controller="AdminCourse" asp-action="DeleteLecturer"
                           asp-route-courseId="@Model.Id" asp-route-LecturerId="@Lecturer.UserId">
                            Delete
                        </a>
                    </td>
                </tr>
            }
        }
    </table>
    <br/>

    <form asp-controller="AdminCourse" asp-action="AddLecturer" asp-route-courseId="@Model.Id" method="post">
        <div class="form-group">
            <label>Select Lecturer:</label>
            <select class="form-control" asp-for="SelectedLecturer" asp-items="@Model.AllTheLecturers"></select>
        </div>

        <input class="btn btn-success" style="background-color:darkseagreen" type="submit" value="Add"/>
        <a class="btn btn-primary" style="background-color: #ADD8E6" asp-controller="AdminCourse" asp-action="Info" asp-route-id="@Model.Id">Back</a>

    </form>

    <br/>
}

@section validation {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

WebClient/Areas/Admin/Views/AdminCourse/Info.cshtml
@using CMSys_project.ViewModels
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Courses";
}

@section Main{
    <h2>Courses</h2>
    <div class="form-group">
        <a class="btn btn-secondary btn-lg" asp-action="Create">Add course</a>
    </div>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>Name</th>
            <th>Department</th>
            <th>Type</th>
            <th>Status</th>
            <th>Lecturers</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>
        @foreach (CourseVM item in Model)
        {
            <tr>
                <td>@item.Name</td>
                <td>@item.Department.Name</td>
                <td>@item.Type</td>
                <td>
                    @{
                        if (item.Status)
                        {
                            <text>New</text>
                        }
                    }
                </td>

                <td>
                    @foreach (LecturerVM Lecturer in item.Lecturers)
                    {
                        <li>
                            @Lecturer.User.FullName
                        </li>
                    }
                </td>
                <td>
                    <a class="btn btn-outline-dark" asp-action="Edit" asp-controller="AdminCourse" asp-route-id="@item.Id">Edit</a>
                    <a class="btn btn-outline-dark" asp-action="Delete" asp-controller="AdminCourse" asp-route-id="@item.Id">Delete</a>
                    <a class="btn btn-outline-dark" asp-action="EditLecturer" asp-controller="AdminCourse" asp-route-id="@item.Id">Edit Lecturers</a>
                    <a class="btn btn-outline-dark" asp-action="Profile" asp-controller="AdminCourse" asp-route-id="@item.Id">Info</a>
                </td>
            </tr>
        }
        </tbody>
    </table>
}

WebClient/Areas/Admin/Views/AdminCourse/Profile.cshtml
@using CMSys_project.ViewModels
@model CMSys_project.ViewModels.CourseVM;
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Courses";
}

@section Main{
    <h2>Courses</h2>
    <div class="form-group">
    </div>
    <thead>
    </thead>
    <body>
    <h2>@Model.Name</h2>
    <br/>
    <h4>Lecturers</h4>
    @foreach (LecturerVM Lecturer in Model.Lecturers)
    {
        <li>
            @Lecturer.User.FullName
        </li>
    }
    <br/>

    <h6>Type: @Model.Type</h6>
    <h6>Arrangement: @Model.Schedule</h6>
    <br/>

    <h5>Description</h5>
    <p>
        @Model.Description
    </p>
    <a class="btn btn-outline-dark" asp-action="Info" asp-controller="AdminCourse">Back</a>
    </body>

}