WebClient/Areas/Admin/Controllers/AdminUserController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using AutoMapper;
using BLL.Contract;
using CMSys_project.ViewModels;
using Domain.Entities.UserEntities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace CMSys_project.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Route("Admin/User")]
    [Authorize(Roles = "Administrator")]
    public class AdminUserController : Controller
    {
        private readonly IMapper _iMapper;
        private readonly IMembershipService _iMembershipService;

        public AdminUserController(IMembershipService iMembershipService, IMapper iMapper)
        {
            _iMembershipService = iMembershipService;
            _iMapper = iMapper;
        }

        [Route("Info")]
        public IActionResult Info()
        {
            IEnumerable<UserVM> LecturerVMs =
                _iMapper.Map<IEnumerable<Domain.Entities.UserEntities.User>, IEnumerable<UserVM>>(_iMembershipService
                    .GetAllUsers());
            return View("Info", LecturerVMs);
        }

        [Route("Edit/{id}")]
        [HttpGet]
        public IActionResult Edit(Guid id)
        {
            try
            {
                Domain.Entities.UserEntities.User user = _iMembershipService.GetUser(id);
                UserVM userVm = _iMapper.Map<Domain.Entities.UserEntities.User, UserVM>(user);

                userVm.RoleVm = _iMapper.Map<IEnumerable<Role>, IEnumerable<RoleVM>>(user.UserRole.Select(x => x.Role))
                    .ToList();
                List<RoleVM> allRoles = _iMapper
                    .Map<IEnumerable<Role>, IEnumerable<RoleVM>>(_iMembershipService.GetAllRoles()).ToList();

                List<string> roleNames = userVm.RoleVm.Select(x => x.Name).ToList();
                List<RoleVM> aList = new List<RoleVM>();
                foreach (RoleVM roleVm in allRoles)
                {
                    RoleVM role = new RoleVM
                    {
                        Name = roleVm.Name,
                        Selected = roleNames.Contains(roleVm.Name),
                        RoleId = _iMembershipService.GetAllRoles().First(x => x.Name.Equals(roleVm.Name)).RoleId
                    };
                    aList.Add(role);
                }

                userVm.RoleVm = aList;

                return View(userVm);
            }
            catch
            {
                ViewBag.Message = "User was not found";
                return View("Error");
            }
        }

        [Route("Edit/{id}")]
        [HttpPost]
        public IActionResult Edit(UserVM userVm, IFormFile photo)
        {
            Domain.Entities.UserEntities.User user = _iMembershipService.GetUser(userVm.Id);
            user.WorkEnd = userVm.WorkEnd;
            List<UserRole> userRole = new List<UserRole>();
            foreach (var roleVm in userVm.RoleVm.Where(x => x.Selected.Equals(true)))
            {
                userRole.Add(new UserRole
                {
                    RoleId = roleVm.RoleId,
                    UserId = user.Id,
                    User = user,
                    Role = _iMembershipService.GetRole(roleVm.RoleId)
                });
            }
            userRole.Add(
                new UserRole
                {
                    RoleId = _iMembershipService.GetAllRoles().First(x => x.Name.Equals("User")).RoleId,
                    Role = _iMembershipService.GetAllRoles().First(x => x.Name.Equals("User")),
                    User = user,
                    UserId = user.Id
                }
                );
            if (photo != null && photo.Length > 0)
            {
                using (MemoryStream ms = new MemoryStream())
                {
                    photo.CopyTo(ms);
                    user.Photo = ms.ToArray();
                }
            }

            if (userRole.Count == 0)
            {
                ViewBag.Message = "User must has at least 1 role!";
                return View("Error");
            }

            try
            {
                _iMembershipService.EditUser(user, userRole);
                return RedirectToAction("Info");
            }
            catch (Exception)
            {
                ViewBag.Message = "User was not found";
                return View("Error");
            }
        }
    }
}

WebClient/Areas/Admin/Views/AdminUser/Edit.cshtml
@model CMSys_project.ViewModels.UserVM

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Add Course";
}
@section Main{
    <form asp-action="Edit" asp-controller="AdminUser" asp-route-id="@Model.Id" enctype="multipart/form-data">
        <div class="form-group">
            <label asp-for="WorkEnd" class="control-label">Date of work end</label>
            <input type="date" asp-for="WorkEnd" class="form-control" />
            <span asp-validation-for="WorkEnd"></span>
        </div>
        @*//hidden value true*@
        <div class="form-group">
            @for (int i = 0; i < Model.RoleVm.Count; i++)
            {
                <input asp-for="@Model.RoleVm[i].Selected" disabled="@Model.RoleVm[i].Name.Equals("User")" type="checkbox"/>
                <input asp-for="@Model.RoleVm[i].Name" type="hidden"/>
                <input asp-for="@Model.RoleVm[i].RoleId" type="hidden"/>
                <label asp-for="@Model.RoleVm[i].Name" checked="checked">@Model.RoleVm[i].Name</label>
            }
        </div>
        <div class="form-group">
            <label asp-for="Photo"></label>
            <br />

            @{
                if (Model.Photo.Length == 0)
                {
                    <text>No photo</text>
                }
                else
                {
                    <img style="display: inline-block; width: 190px; height: 256px"
                         src="data:image;base64,@Convert.ToBase64String(Model.Photo)" alt="User image" />
                }
            }
            <br/>
            <input type="file" asp-for="Photo" />
        </div>
        <div class="form-group">
            <input type="submit" value="Send" class="btn btn-success" style="background-color:darkseagreen"/>
        </div>
    </form>
}
@section validation {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

WebClient/Areas/Admin/Views/AdminUser/Info.cshtml
@using CMSys_project.ViewModels
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Add Course";
}

@section Main{
    <h2>Users</h2>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>Name</th>
            <th>Photo</th>
            <th>Department</th>
            <th>Faculty</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>
        @foreach (UserVM item in Model)
        {
            <tr>
                <td>@item.Email</td>
                <td>
                    @{
                        if (item.Photo.Length == 0)
                        {
                            <text>No photo</text>
                        }
                        else
                        {
                            <img style="display: inline-block; height: 128px; width: 95px;"
                                 src="data:image;base64,@Convert.ToBase64String(item.Photo)" alt="User image"/>
                        }
                    }
                </td>
                <td>@item.Department</td> 
                <td>@item.Faculty</td>
                <td>
                    <a class="btn btn-outline-dark" asp-action="Edit" asp-controller="AdminUser" asp-route-id="@item.Id">Edit</a>
                </td>
            </tr>
        }
        </tbody>
    </table>
}